resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
vars/common.groovy
vars/gen_jobs.groovy
vars/mbedtls.groovy
vars/scripts.groovy

If `scripts/min_requirements.py` exists (added by https://github.com/ARMmbed/mbedtls/pull/5197), run it.
Keep the CI working as before for branches that don't have it. Branches that need jinja2 will need to have `scripts/min_requirements.py` and thus to be based on https://github.com/ARMmbed/mbedtls/pull/5197.
Prerequisites:
[see issue history for validation on older commits]
On 775873dd7a0d7198b26f70e35c0b6700418059f5:
* `development` complete — https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/340/ → PASS
* `development_2.x` complete — https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/339/ → PASS
* `mbedtls-2.16` complete — https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/333/ → PASS
* `dev/gilles-peskine-arm/pip-requirements` at …

Use in-tree python package requirements if available

---

vars/gen_jobs.groovy

I forgot about the ABI check job in https://github.com/ARMmbed/mbedtls-test/pull/18.
Testing:

Install Python modules if needed when running abi_check

---

resources/docker_files/README.md

The example shows how to build the ubuntu-18.04 image so set the
correct version on the Dockerfile parent folder.
Signed-off-by: Leonardo Sandoval <leonardo.sandoval@linaro.org>

Fix version on docker build instructions

---

vars/gen_jobs.groovy

Add a job to push to the coverity scan branch to the nightly tests.
Coverity push is conditional on new environment variable PUSH_COVERITY, so future nightly jobs will have to have that variable turned on in order to enable.
Coverity push will only happen if the nightly is running on development branch.
This closes https://github.com/ARMmbed/mbedtls-test/issues/14
This has been tested via the TEST_BRANCH variable, and found to be working : https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/361/

Adding coverity push to nightly job

---

vars/common.groovy

Make nightly results easier to see at a glance (and filter) by adding the branch name to the email subject.
Successful test run here: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/366/

Add branch name to nightly email notifications

---

vars/environ.groovy

Signed-off-by: Arthur She <arthur.she@linaro.org>
Test job on the staging CI
[mbedtls-release-ci-testing](https://ci.staging.trustedfirmware.org/view/Arthur%20MbedTLS/job/arthur-mbedtls-release-ci-testing/10/console)
[mbed-tls-restricted-pr-test-parametrized](https://ci.staging.trustedfirmware.org/view/Arthur%20MbedTLS/job/arthur-mbed-tls-restricted-pr-test-parametrized/4/console)

Enable FreeBSD test on OpenCI

---

vars/common.groovy

Currently we aren't passing any host variables through to the docker containers, meaning that we were only building the library with `make -j2` on FreeBSD and Windows.
Test runs with the patch applied:
mbedtls-release-ci-testing:  https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/397/
mbed-tls-pr-test-parametrized: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/240/

Use the host MAKEFLAGS variable in containers

---

vars/scripts.groovy

Calling `vcvarsall.bat` before `min_requirements.py` was interfering with installing python source distributions on Windows.
Example log for run without this patch, showing the bug:
https://ci.staging.trustedfirmware.org/view/Arthur%20MbedTLS/job/arthur-mbed-tls-nightly-tests/45/execution/node/109/log/
Example log of the equivalent step for a run with this patch applied:
https://ci.staging.trustedfirmware.org/view/Arthur%20MbedTLS/job/arthur-mbed-tls-nightly-tests/48/execution/node/1915/log/?consoleFull

Build required python sdists with default compiler

---

vars/mbedtls.groovy

The message of an Exception may be null.
This situation shows up in particular if a test run is cancelled due to a newer job for the same PR being launched.
Eg. https://ci.trustedfirmware.org/job/mbed-tls-pr-merge/job/PR-6436-merge/3/
Patched PR-HEAD run in the same scenario:
[Cancelled job](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-head/3/)  
[Successor job](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-head/4/)
[Failure of pre test checks](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-919-head/1/)

Fix null pointer exception in error message parsing

---

vars/mbedtls-release-Jenkinsfile
vars/mbedtls.groovy

This makes the steps show up on the Blue Ocean view of the test runs.
Without this PR, failures in the Result analysis process would only show up in Github status reports, and the old Jenkins UI.
Eg. see [this comment](https://github.com/Mbed-TLS/mbedtls/issues/6466#issuecomment-1294474977) in Mbed-TLS/mbedtls#6466

Add stage declaration for Result analysis phase

---

vars/mbedtls.groovy

This PR restricts what we consider as PR activity for the purposes of nightly merge builds to the following:
1. Manual pushes of the PR branch
2. Manual CI runs on the PR
3. Reviews of the PR
Since Github doesn't track when the PR was last pushed in a convenient way, we record the "last update timestamp" in our environment, which can be retrieved by subsequent CI runs, and update this timestamp if the CI is triggered by anything other than the nightly repo scan.
If none of the above timestamps are available (eg. in the initial CI run on a PR after this is merged, where there are no previous reviews), we fall back to the `updated_at` property that we have been using so far - this metric includes things like comments, label changes, etc.

Only consider pushes, manual CI runs and reviews as "PR activity" for the purposes of nightly builds

---

vars/analysis.groovy
vars/gen_jobs.groovy

When a job fails, provide an artifact `failures.csv` (or `failures.csv.xz` if it's large) containing just the failed test cases from the `outcomes.csv`. The complete outcome file is very large but the list of failed test cases is typically a lot smaller, so this makes it easier to download and analyze the failures and only wastes a very small amount of space on the server.
CI runs on https://github.com/Mbed-TLS/mbedtls-test/pull/72/commits/c86f7ebb5d71f420569ca091c8b115575575661f:
* [Passing](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/420/), expecting no `failures.csv` → OK
* [Build failures but no failing test case](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/419/), expecting empty `failures.csv` → OK
* [Failed a few test …

Upload a failure list as a Jenkins artifact

---

vars/common.groovy
vars/gen_jobs.groovy
vars/mbedtls.groovy

Prevent the catching of unrelated exceptions, and re-throw the caught exceptions where appropriate.

Exception reporting fixes

---

vars/common.groovy
vars/gen_jobs.groovy

If an `all.sh` component is supported only on Ubuntu 20.04, and not on 18.04 or 16.04, it is silently skipped. Fix this.
Test runs:
* [Branch that has a 20.04-only job](https://github.com/gilles-peskine-arm/mbedtls/tree/all.sh-modern-ubsan): https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/428/ → OK (pass, 20.04 job ran as expected)
* development: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/430/ → OK

Fix dispatch to Ubuntu 20.04

---

vars/common.groovy

This matches the previous timeout for Windows jobs.
Signed-off-by: Bence Szépkúti <bence.szepkuti@arm.com>

Increase timeout for all.sh jobs to 120 minutes

---

README.md
resources/docker_files/README.md

Trying to make it more discoverable how to fetch images used by the CI.
See also https://github.com/Mbed-TLS/mbedtls/pull/6789

Make the CI Docker images more discoverable.

---

vars/common.groovy

"common" inside common.groovy refers to the groovy class - not the singleton instance.
Pre-patch tests:
[Internal][1] [OpenCI][2]
Post-patch tests:
[Internal][3] [OpenCI][4]
[1]:https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/432/
[2]:https://ci.staging.trustedfirmware.org/view/Mbed-TLS/job/mbedtls-release-ci-testing/1/
[3]:https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/433/
[4]:https://ci.staging.trustedfirmware.org/view/Mbed-TLS/job/mbedtls-release-ci-testing/2/

Fix release job

---

vars/common.groovy

Missed reference to "common" when refactoring wrap_report_errors().
Same issue as in #92, just on the error path.
Pre-path tests:
[Internal][1] [OpenCI][2]
Post-patch tests:
[Internal][3] [OpenCI][4]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/PR-759-head/7/
[2]: https://ci.staging.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/job/PR-759-head/1/
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/PR-759-head/9/
[4]: https://ci.staging.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/job/PR-759-head/2/

Fix error reporting

---

vars/analysis.groovy
vars/mbedtls-gather-timestamps-Jenkinsfile

Introduce a job which collects the timestamps produced by the PR and nightly release jobs in the past 24 hours, and produces CSV and JSON files for easy consumption of this data.
In the process, it upgrades version 0 JSON timestamps (the current format) to include all the additional data included in the CSV file. I will file a separate PR to move us to this format when gathering timestamps in the first place.
Test run:
Internal CI: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-gather-timestamps/56/
Question for reviewers / users. Would it be helpful to be able to configure the timespan to gather timestamps from?
The current idea is to run this job automatically every night, so we can preserve the timestamps of various jobs for a while longer after they are pruned due to eg. closed PRs. …

Add gather timestamps job

---

vars/analysis.groovy
vars/common.groovy
vars/mbedtls-release-Jenkinsfile
vars/mbedtls.groovy

This PR improves the timestamp gathering in the release jobs by adding inner timestamps to the main job, bringing it up to parity with the PR jobs.
It also improves the timestamping of both kinds of jobs by recording timestamps for the analysis stage, breaking out the timestamp write-out process into a separate stage in the process.
Test runs:
Internal CI:
[Release test (good, development)][1]
[Release test (fail CMake)][2]
[PR test (good)][3]
[PR test (fail CMake)][4]
OpenCI:
[Release test (good, development)][5]
[Release test (fail CMake)][6]
[PR test (good)][7]
[PR test (fail CMake)][8]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/453/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/454/
[3]: …

Improve timestamp gathering in release and pr jobs

---

vars/mbedtls.groovy

Since we've removed most tests from PR-merge we can afford to run it for all open PRs.
Test runs:  
- PR-merge:
- [Internal][1]
- [Open CI][2]
- [PR-head][3]
- [release][4]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-merge/117/
[2]: https://ci.staging.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/6/
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/PR-906-head/55/
[4]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/489/console

Remove cutoff for running nightly PR-merge jobs

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

This is prepare for [checking data_files](https://github.com/Mbed-TLS/mbedtls/issues/7729)
That script will run test with faketime
Test jobs on 6d32bea9647310e784e2d7e8eb05dc1fa03dd945 (running just Linux tests, since there are only Docker file updates):
* [OpenCI](https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbedtls-release-ci-testing/22/) → PASS
* [internal CI](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/496/) → PASS

Add faketime package

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

`xxd` command is used for generating malformed data files. And https://github.com/Mbed-TLS/mbedtls/pull/7866 introduces tests for data files.

Add xxd for data file regenerating tests

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

`hexdump` command is used for generating malformed data files. And https://github.com/Mbed-TLS/mbedtls/pull/7866 introduces tests for data files.
`hexdump` is provided by `bsdmainutils` or `bsdextrautils`.

Add hexdump command

---

resources/docker_files/README.md
resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

This commit updates the Ubuntu 16.04 docker file to include the earliest versions of GCC (4.7) and Clang (3.5) available in 16.04. For Ubuntu 22.04 the latest compiler versions of GCC (12) and Clang (16) are installed.
Also creates couple of symlinks of those compilers for simplified usage in the all.sh script.
`all.sh` will start using the new compiler versions in https://github.com/Mbed-TLS/mbedtls/pull/7968 and https://github.com/Mbed-TLS/mbedtls/pull/7969.
Resolves #110

Add earliest and latest compilers

---

vars/checkout_repo.groovy
vars/common.groovy
vars/environ.groovy
vars/mbedtls.groovy

We report test failures to Github early, which causes Github to delete merge queue branches while they are still being tested. These deletions are reported to Jenkins via webhooks, which causes the `scm` variable to degenerate into a [NullSCM][1] object.
Handle such cases by extracting the needed information from `scm` early, and checking for the `NullSCM` type when performing checkouts.
This patch marks stages where we attempted to check out a NullSCM object as "unstable", which shows up as yellow on Blue Ocean. This helps quickly identify the  test that originally caused the failure (since its stage will show up as red).
~~At the time of writing, the stages on OpenCI turn yellow, as intended -  but the Internal CI needs a (fairly trivial) plugin upgrade for the stages to show up as …

Fix error reporting in case a branch is deleted while being tested

---

resources/docker_files/arm-compilers/Dockerfile
vars/gen_jobs.groovy

This lets us refactor the arm-compilers Dockerfile, and circumvents any issues with changes to Docker's layer caching behaviour.
Test runs:
- [OpenCI][2]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/538/
[2]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/82/

Copy the Arm compilers from a fixed base image

---

resources/docker_files/arm-compilers/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
vars/checkout_repo.groovy
vars/common.groovy
vars/gen_jobs.groovy
vars/mbedtls.groovy
vars/scripts.groovy

Use it to hotfix https://github.com/Mbed-TLS/mbedtls/pull/8250 on branches forked before https://github.com/Mbed-TLS/mbedtls/pull/8249. That is, with this pull request, we can run the CI on older branches whose `jsonschema` dependency breaks our CI.
Status: ready if this passes CI (currently not expecting failures except maybe abi-api-check).
CI runs on 90a27efd6903499db93cf1c003d89cfecc675b4b or 13061ca754d15dbe59a9aef86acf1d4554d82fd3 (they have identical contents):
* `development` before #8249, [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/83/) → pass, with `override.requirements.txt` attached
* `development` after #8249, [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/84/) → pass, with no requirements override
* `mbedtls-2.28`, …

Add mechanism to override Python requirements

---

vars/common.groovy
vars/mbedtls.groovy

Only run PR job if one of the following is true:
- The author of the PR has write access to the repo the PR is targeting
- The job is triggered by the Github merge queue (thus the PR has been reviewed by a gatekeeper)
- The job was started manually from the Jenkins UI
Test runs:
- Push to a PR authored by a non-member (PR-merge):
- [OpenCI][2]
- Manual run of a PR by a non-member (PR-merge):
- [Internal CI][3]
- [OpenCI][4]
- Manual run of a PR with an expected failure (PR-head):
- [Internal CI](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-759-head/23/)
- Push to a PR authored by a team-member (PR-head).
- [Internal CI][5]
- [OpenCI][6]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/j …

Restrict automatic runs of PR jobs

---

vars/mbedtls.groovy

The logic for faking tests that are required for but do not run when testing a PR in the merge queue was broken in #129.
This PR restores the logic that was used prior to that PR.
CI runs:
- [Merge queue run][1] before this PR on Mbed-TLS/mbedtls#8328
- [Merge queue run][2] with this PR on Mbed-TLS/mbedtls#7959
(The test commit in Mbed-TLS/mbedtls#7959 states that it introduces a conflict with the base branch, but to expedite testing this PR it was repurposed and the conflict was removed from the base branch. The expected result for its merge queue run is SUCCESS.)
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-head/job/gh-readonly-queue%252Fdevelopment%252Fpr-8328-e7ebec6723b61bd54800f649b1391e980edf2fbd/1/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/ …

Restore logic for tests skipped in merge queue

---

vars/gen_jobs.groovy

Calling `get_branch_information()` inside an `instrumented_node_job()` block causes the nesting of two `node()` blocks. This makes the script wait for a new node to be allocated on an executor, while still occpying the original executor as well. This slows the CI down considerably, and causes a deadlock if all nodes are occupied by api-abi checking jobs waiting for a node to be allocated.
Test runs:
- [Open CI][2]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-merge/131/
[2]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/10/

Prevent deadlock in api-abi-checking job

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

Start using version numbers in $OPENSSL and $GNUTLS variables, e.g. `$OPENSSL_1`, `$OPENSSL_1_1` and `$OPENSSL_1_1_1` are OpenSSL 1.1.1a. This will allow `all.sh` to reference these versions.
Keep the old names `$OPENSSL_NEXT` etc. pointing to the same versions for backward compatibility: we don't want to break `all.sh` in branches of mbedtls we care about (`development`, `mbedtls-2.28`, as well as open pull requests to these branches and other work in progress). We won't change what these non-numbered variables point to, we'll gradually migrate away from them.
Remove GnuTLS 3.3.8 which was `GNUTLS_LEGACY` and replace GnuTLS 3.4.10 with 3.4.6 which has all the features we need and [one less bugfix](https://github.com/Mbed-TLS/mbedtls-test/pull/122/commits/46a206feb6a0ab89e70c87599dcc642ee4 …

Use version numbers in $OPENSSL and $GNUTLS variables; add OpenSSL 3.0 and 3.1

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

This lets us test building the library with the arm cryptographic extensions.
Builds:
- Ubuntu 16.04 and 20.04
- [OpenCI][2]
- Ubuntu 20.04 and 22.04
- [Internal CI][3]
- [OpenCI][4]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/303/
[2]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-test-parametrized/22/
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/301/
[4]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-test-parametrized/20/

Install the armhf and aarch64 gcc-cross toolchains

---

vars/mbedtls.groovy

We've switched again to making OpenCI the required CI, which runs on the merge queue. So we need to make OpenCI fake the status checks.
This is a minimal emergency fix. I've filed https://github.com/Mbed-TLS/mbedtls-test/issues/139 for more robustness.

Flip the merge queue to OpenCI

---

vars/common.groovy

Changes to the self tests / Open CI seem to have pushed made the windows tests longer, so they regularly take longer than the 2 hour time limit. Increase the timeout so we can unblock windows testing.
Test runs (this commit + extra debug info):
- release-ci-testing
- https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/114/
- https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/115/
- https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/116/
- https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/117/
- https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/118/

Increase Windows testing timeout

---

vars/common.groovy

Filter the all.sh components which are named `component_release_xxx` from PR tests.
Test runs:
- PR tests
- [No filtered components][1] - Mbed-TLS/mbedtls@d9c69d12acebe89dbdc023e66d25c05d84725aa0
- [Valgrind components filtered][2] - bensze01/mbedtls@0354d04d3c5258df49cc7d1adcb5f9598dcb16d6
- Release tests
- [Valgrind components marked, but not filtered][3] - bensze01/mbedtls@0354d04d3c5258df49cc7d1adcb5f9598dcb16d6
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/304/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/305/
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/560/

Do not run all.sh release components in PR jobs

---

vars/analysis.groovy

Improve perf of the analyse-outcomes stage of CI, which especially matters because it's a serial stage of the CI pipeline.
Currently, it takes around 247s to run xz on the CI.
Testing locally, current xz command takes 130s. With -0, it takes 15s (so expect ~28.5s on CI). This increases compressed size from 38 MB to 54 MB.
Using -T8 (8 threads) reduces it further to 2.6s locally (expect ~5s on CI). There's no penalty for going too big on thread count, but no benefit beyond about 8-16.
lzma, gzip, bzip2, zip are all worse.
Also, use grep instead of awk to extract failures, which saves a few more seconds.
CI run: https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-head/detail/PR-8530-head/9/pipeline/

speed up analyze-outcomes stage

---

vars/analysis.groovy

Fix a corner case from #144 that prevents the upload of `outcomes.csv` when there are failed jobs but no failed test cases (e.g. all tests that compile are passing, but there are configurations where the compilation fails).
Test run:
* development, release job (with Windows-2015 failing and causing the problem): [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/126/)
* 2.28, release job (all passing): [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/127/)

Fix generation of failures.csv when there are only non-outcome failures

---

vars/common.groovy

There is a compiler bug around optimizations that's causing an internal error.
- Internal CI
- [development][1]
- [mbedtls-2.28][2]
- OpenCI
- [development][3]
- [mbedtls-2.28][4]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/565/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/566/
[3]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/128/
[4]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/129/

Drop MSVC 2015 testing from nightly builds

---

resources/windows/windows_testing.py
vars/common.groovy
vars/gen_jobs.groovy

Split up the windows tests into individual builds, and group them into ~20 minute sized chucks that share the checkout and python dependency installation steps
CI runs:
- OpenCI:
-  [mbedtls-release-ci-testing][1] (0eba489dca91876e976a0c00b65d523c868a7241)
- PR-head
- [development - good][3]
- [mbedtls-2.28 - good][4]
- [CMake fail][5]
- Internal CI:
- [mbedtls-release-ci-testing][2] (0eba489dca91876e976a0c00b65d523c868a7241)
- PR-head
- [development - good][6]
- [mbedtls-2.28 - good][7]
- [CMake fail][8]
[1]: https://mbedtls.trustedfirmware.org/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/151/pipeline/
[2]: https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-release-ci-testing/detail/mbedtls-release-ci-testing/584/pipeline/ …

Split up windows jobs

---

vars/common.groovy
vars/environ.groovy

We've breached 2 hours in  `all_u16-release_test_valgrind_psa`, so increase the timeout value.
With the current implementation of "silent logging", timeouts also destroy all the logs, so turn verbose logs on for now.
Test run: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/587/

Increase linux testing timeout

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile

Install Python 3.6 on the Ubuntu 16.04 Docker image and make it the default. With this change, our CI now runs with Python ≥3.6 everywhere. Python 3.6 is the oldest version we need to support [for Mbed TLS 2.28 LTS](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-2.28/README.md#tool-versions).
Test runs at a4badb998e13d0f85d7805776fc8a39a9695267d:
* `development`, release : [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/208/). A [log](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/208/execution/node/1682/log/) showing `python3: /usr/local/bin/python3 : Python 3.6.15` on `ubuntu-16.04-*`.
* `mbedtls-2.28`, release: [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/209/)
* `development`, stablity checks: [Internal …

Use Python ≥3.6 everywhere

---

vars/analysis.groovy
vars/gen_jobs.groovy
vars/mbedtls.groovy

[Run result analysis in the same environment as test jobs: in a Docker image, with our Python requirements installed. This does most of the work towards Mbed-TLS/mbedtls#8300: we'll be able to run `make generated_files`.
We could finish resolving  https://github.com/Mbed-TLS/mbedtls/issues/8300 here by running `tests/scripts/check-generated-files.sh -u` here. (Not `make generated_files` because that doesn't exist in 2.28.) But I would prefer to pull the switch in an `mbedtls` pull request that changes `analyze_outcomes.py` to run `make generated_files`. I'm open to counter-arguments though.
Also, as a result of refactoring:
* Resolves https://github.com/Mbed-TLS/mbedtls-test/issues/134
* Resolves maybe https://github.com/Mbed-TLS/mbedtls-test/issues/120 in passing. This is not fully …

Run result analysis in Docker

---

vars/mbedtls.groovy

The version of Git on 16.04 does not attempt to fetch submodule commits by hash, causing CI failures if PRs are submitted to the framework repo from forks.
Tests (PR-merge):
- development: [Internal][1] / [Open CI][2]
- mbedtls-3.6:   [Internal][3] / [Open CI][4]
- mbedtls-2.28: [Internal][5] / [Open CI][6]
- ABI break:       [Internal][7] / [Open CI][8]
Tests with the framework submodule pointing to a commit only found in a fork:
- pre-fix:   [Internal][9] / [Open CI][10]
- post-fix: [Internal][11] / [Open CI][12]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-merge/139/
[2]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/18/
[3]: …

Run API-ABI check on Ubuntu 18.04

---

resources/windows/windows_testing.py

For the testing on Windows following the move of crypto test suites into the tf-psa-crypto directory we need to create a seedfile in `tf-psa-crypto/tests/`. It seems it has been done for the previous repo split but with a different crypto directory name. Thus update this name.

Update crypto directory name

---

vars/analysis.groovy
vars/gen_jobs.groovy

This PR restores the intended behaviour of the `analysis` step, that it runs on a `helper-container-host` instance.
The current upstream code reserves a `helper-container-host` but actually runs all the tests on a dfferent, `container-host` executor
Test runs:
- OpenCI
- Supposed to pass
- development: [PR-head][openci-development-head] [PR-merge][openci-development-merge]
- mbedtls-3.6: [PR-head][openci-3.6-head] [PR-merge][openci-3.6-merge]
- mbedtls-2.28: [PR-head][openci-2.28-head] [PR-merge][openci-2.28-merge]
- Supposed to fail
- [Fail all CMake builds][openci-cmake]
- [Unexecuted test][openci-unexecuted]
- Internal CI
- Supposed to pass
- development: [PR-head][internal-development-head] [PR-merge][internal-development-merge]
- mbedtls-3.6: [PR-head][internal-3.6-head] …

Fix analysis step to use only a single helper-container-host executor

---

vars/gen_jobs.groovy

Trying to push shallow commits was failing due to git not being able to verify that this was a fast-forward operation.
CI test run: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/716/

Fix pushing to the coverity_scan branch

---

resources/docker_files/arm-compilers/Dockerfile
resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile
vars/common.groovy
vars/gen_jobs.groovy

Also upgrade to Arm Compiler 6.21 and drop testing on Arm Compiler 5
Test runs:
- Internal CI
- pr-ci-testing
- [development][1]
- [mbedtls-3.6][2]
- [mbedtls-2.28][3]
- release-ci-testing
- [development][7]
- [mbedtls-3.6][8]
- [mbedtls-2.28][9]
- OpenCI
- pr-ci-testing
- [development][4]
- [mbedtls-3.6][5]
- [mbedtls-2.28][6]
- release-ci-testing
- [development][10]
- [mbedtls-3.6][11]
- [mbedtls-2.28][12]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-head/123/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-1233-head/9/
[3]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-850-head/11/
[4]: …

Switch to using User-based Licensing on the OpenCI

---

src/org/mbed/tls/jenkins/BranchInfo.groovy
src/org/mbed/tls/jenkins/JobTimestamps.groovy
vars/analysis.groovy
vars/checkout_repo.groovy
vars/common.groovy
vars/environ.groovy
vars/gen_jobs.groovy
vars/mbedtls-pr-test-Jenkinsfile
vars/mbedtls-release-Jenkinsfile
vars/mbedtls.groovy

This PR enables the testing of the framework repo, by adapting the existing jobs to allow overriding the version of the framework checked out by the CI, as well as enabling the testing of multiple branches of Mbed TLS in a single job.
The framework version is controlled by the newly defined parameters `FRAMEWORK_REPO` and `FRAMEWORK_BRANCH`, while `MBEDTLS_BRANCH` has been extended to allow specifying multiple branches separated by `,`.
For automatic PR testing, `mbedtls.run_framework_pr_job()` is added as an entrypoint, which is called by the Jenkinsfile added by the companion PR Mbed-TLS/mbedtls-framework#33
Tests:
- Runs with framework version override enabled:
- [mbed-tls-framework-multibranch][1]
- [mbed-tls-pr-test-parametrized][2]
- [mbedtls-release-ci-testing][3]
- Runs without a …

Adapt PR and release jobs to enable testing of the Framework repo

---

vars/mbedtls.groovy

When running on a branch rather than a PR (eg. on a merge-queue branch), the Git plugin doesn't set CHANGE_BRANCH - in these cases, BRANCH_NAME contains the name of the branch.
Test runs:
- Internal CI:
- [Merge queue][1]
- [PR-head][2]
- OpenCI:
- [Merge queue][3]
- [PR-head][4]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/dev%252Fdgreen-arm%252Fci-testing-development/2/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-head/125/
[3]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/job/dev%252Fdgreen-arm%252Fci-testing-development/2/
[4]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-head/27/

Use BRANCH_NAME in run_pr_job if CHANGE_BRANCH is unset

---

vars/common.groovy
vars/mbedtls-release-Jenkinsfile
vars/mbedtls.groovy

This call was missed / accidentally dropped during a rebase of commit 8d9b2b78df05a3bd0ef90e4cfe021373fc65c652.
Also initialize infos at declaration, so an early failure doesn't result in a null pointer dereference in the finally block.
Test runs:
- Internal CI
- [E-mail set][1]
- [E-mail unset][2]
- OpenCI
- [E-mail set][3]
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/727/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/728/
[3]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/287/

Fix sending test-result E-mails

---

vars/analysis.groovy
vars/gen_jobs.groovy

This PR fixes several issues that occur when the name of the Mbed TLS branch being tested is included in file or stash names. This happens when we test multiple branches at once, eg. in framework PRs or if multiple branches are specified in a parameterized job.
In addition, the second commit breaks gen_docker_job into sub-stages, so that the result analysis display on Blue ocean is not overwhelmed by the unstash stages. 
Fixes #127 
Test runs:
- development: good + skipped/failed tests
- [OpenCI][2]
- development: release job
- [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/297/)
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/372/
[2]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-test-parametrized …

Fix result analysis in failed multi-branch test runs

---

vars/common.groovy

CI runs:
- release-ci-testing
- [development][1]
- [mbedtls-3.6][2]
- [mbedtls-2.28][3]
[1]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/294/
[2]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/295/
[3]: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/296/

Enable Arm on-target testing on the OpenCI

---

vars/checkout_repo.groovy
vars/environ.groovy
vars/tf_psa_crypto.groovy

Changes and fixes needed to add test jobs for the crypto repo
Test Runs:
- Internal CI
- Runs with a psa crypto version override enabled
- Mbed-TLS/mbedtls-restricted@a23e11c7b14458a5e17755c545cdac681b20260d + Mbed-TLS/TF-PSA-Crypto@4fd370f77b1852a68b5725cd9c7d498f3bfc8265
- [mbed-tls-pr-test-parametrized][1]
- [mbedtls-release-ci-testing][2]
- Runs with a psa crypto and framework version overrides enabled
- Mbed-TLS/mbedtls-restricted@a23e11c7b14458a5e17755c545cdac681b20260d + Mbed-TLS/TF-PSA-Crypto@4fd370f77b1852a68b5725cd9c7d498f3bfc8265 + Mbed-TLS/mbedtls-framework@f1119c2e80d0a3ce1260fbf3714f5955b4abd026
- [mbed-tls-pr-test-parametrized][3]
- [mbedtls-release-ci-testing][4]
- Runs without a submodule version override
- Mbed-TLS/mbedtls-restricted@a23e11c7b14458a5e17755c545cdac681b2026 …

Add test job for crypto repo

---

README.md
resources/docker_files/README.md
resources/docker_files/list-docker-image-tags.sh
resources/docker_files/run.sh

Before this PR, if one tries to follow this repo's top-level Readme, things will fail in two places:
1. `scripts/min_requirement.py --user` fails with permission issues. This has been the case for a long time. Fixed by changing `run.sh`.
2. `docker pull` fails. This is new since the tags now include the architecture. Fixed by updating the Readme.

Make readme work

---

vars/common.groovy
vars/mbedtls.groovy

Blue Ocean doesn't display nested parallel stages correctly, so instead
refactor get_branch_info and check_every_all_sh_component_will_be_run to
handle multiple branches at once.
Also separate the unexecuted components check to its own stage, because Blue Ocean doesn't display any "single threaded" steps that share a stage with a `parallel` step
CI runs: 
- Supposed to pass:
- Single branch
- PR-head
- [OpenCI][2]
- Release test
- [Internal CI][3]
- [OpenCI][4]
- Multi-branch
- PR-head
- [Internal CI][5]
- [OpenCI][6]
- Release test
- [Internal CI][7]
- [OpenCI][8] 
- Supposed to fail (unexecuted components):
- Single branch
- PR-head
- [Internal CI][9]
- [OpenCI][10]
- Multi-branch
- PR-head
- [Internal CI][13]
- [OpenCI][14]
[1]: …

Fix visualization of multi-branch info gathering and unexecuted components test

---

README.md
developer_guide.md

* Describe the general structure of the CI and the CI scripts.
* Write a few points of advice. There could be plenty more.
* Write a bit of guidance on validating CI changes.
There are no completeness goals here. I will take requests but I don't intend to spend much more time on this. Follow-ups are very welcome.

Create a developer guide

---

resources/docker_files/ubuntu-22.04/Dockerfile

Temporarily make a recent GCC snapshot available for testing. We make it available separately, not as gcc-latest, because it is known to break current branches (https://github.com/Mbed-TLS/mbedtls/issues/9814).
Test jobs:
* [OpenCI, branch using GCC 15](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/312/) → OK, [component using GCC 15](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/312/execution/node/5584/log/) failed as expected (the branch under test doesn't have the bug fix)
* [Internal CI, branch using GCC 15](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/747/) →

Build a GCC 15 snapshot

---

resources/docker_files/arm-compilers/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile
vars/gen_jobs.groovy

Use a python virtual environment when installing pip packages via min_requirements.py. This prevents the installed packages from interfering with the host system.
It also works around spurious build failures when installing said packages. Fixes https://github.com/Mbed-TLS/mbedtls-test/issues/194
Test runs:
- development
- Internal CI
- [mbed-tls-pr-test-parametrized][1]
- Open CI
- [mbed-tls-restricted-pr-test-parametrized][2] 
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/448/
[2]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-test-parametrized/96/

Use a venv for min_requirements.py on Linux and FreeBSD

---

resources/docker_files/ubuntu-16.04/Dockerfile
resources/docker_files/ubuntu-18.04/Dockerfile
resources/docker_files/ubuntu-20.04/Dockerfile
resources/docker_files/ubuntu-22.04/Dockerfile

3.6 and development want `OPENSSL_NEXT` to be 3.1.2.
In `all.sh` this is forced, but not in `basic-build-test.sh` (used by the coverage part of the release job), or when invoking `ssl-opt.sh` directly (which does not happen on the CI but might when using the Docker images for debugging).
As a result, `basic-build-test.sh` has been failing in the 3.6 release CI (because the new tests crucially rely on `OPENSSL_NEXT` being 3.x).
This can be fixed by updating `OPENSSL_NEXT` in the docker images. We couldn't do it previously because 2.28 was still relying on it being 1.1.1a, but now that 2.28 is EOL we're finally free.
(Note that in the long run, the plan is to no longer set `OPENSSL_NEXT` or `OPENSSL_LEGACY` in the Docker files. But first we need to update all script to use named version …

Update OPENSSL_NEXT to what 3.6 and development use

---

resources/docker_files/ubuntu-22.04/Dockerfile

Now that [GCC 15 is released](https://gcc.gnu.org/gcc-15/changes.html), upgrade to the official release. Let's not keep a development snapshot any longer than we have to.
I'm still building from source because there are no official packages either from GNU (as a habit, they only distribute sources) or from Ubuntu ([Ubuntu have some toolchain previews](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test), but they don't backport to older releases).
(As a reminder, we have GCC 15 in our CI because [it revealed a high-impact bug in our code](https://github.com/Mbed-TLS/mbedtls/issues/9814).)
Test jobs (on https://github.com/Mbed-TLS/mbedtls/pull/10159):
* [internal CI](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/803/)
* …

Update GCC 15 snapshot to the 15.1.0 release

---

resources/windows/windows_testing.py
vars/common.groovy
vars/gen_jobs.groovy
vars/scripts.groovy

Resolves https://github.com/Mbed-TLS/mbedtls-test/issues/202. Also resolves https://github.com/Mbed-TLS/mbedtls-test/issues/27.
Scope: I've deliberately made a minimal set of changes. There are probably many simplifications we can make, but that was already the case before (we stil have code related to branches older than 2.18 when we didn't require a C99 compiler!). The current setup is simpler than it might become in the future, however, because currently it's fine to test all branches against the same VS version, but there will probably be times when we want different versions in LTS branches.
Test jobs:
* [release job, mbedtls/development, OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/358/) → looks ok to me (passed and seems to have used the intended VS …

Switch MSVC builds to Visual Studio 2017

---

vars/checkout_repo.groovy

This PR prevents / silences the warnings in the normal testing flow introduced by #206 
Test runs:
- mbedtls-3.6: PR-head
- [OpenCI][1]
- [Internal CI][2]
- development: PR-head
- [OpenCI][3]
- [Internal CI][4]
[1]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-1233-head/20/
[2]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/job/PR-1233-head/24/
[3]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-head/49/
[4]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-head/144/

Prevent git warnings during normal testing flow

---

vars/common.groovy

Workaround for https://github.com/Mbed-TLS/mbedtls-test/issues/213
Combined test runs with Mbed-TLS/mbedtls#10302:
- [Open CI](https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-test-parametrized/164/)
- [Internal CI](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/516/)

Disable ipv6 networking inside docker

---

vars/gen_jobs.groovy

Taking the lock before we are running on a node is preventing the priority sorter from properly prioritizing merge-queue jobs.
Invert the order of taking the "locks" (node -> docker-image), to fix this priority inversion.
Test runs (#216 cherry-picked on top of #212) :
- development
- [Open CI][2]
**PLEASE NOTE**: Care should be taken when merging this PR, since the interaction between runs that still use the old CI scripts (eg. started before the merge) and new runs could cause a deadlock. It would be best to merge it in a quiet period on the CI.
[1]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-test-parametrized/518/
[2]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-test-parametrized/164/

Fix priority inversion in init-docker-images stage
